// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {usbdetector} from '../models';
import {main} from '../models';

export function GetRemovableDrives():Promise<Array<usbdetector.DriveInfo>>;

export function Greet(arg1:string):Promise<string>;

export function LoadConfig():Promise<main.Config>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SelectFolder(arg1:string):Promise<string>;
