// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRemovableDrives() {
  return window['go']['main']['App']['GetRemovableDrives']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}
