// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelImport() {
  return window['go']['importer']['ImportService']['CancelImport']();
}

export function GenerateThumbnail(arg1) {
  return window['go']['importer']['ImportService']['GenerateThumbnail'](arg1);
}

export function GenerateThumbnailsForFiles(arg1, arg2) {
  return window['go']['importer']['ImportService']['GenerateThumbnailsForFiles'](arg1, arg2);
}

export function GetProgress() {
  return window['go']['importer']['ImportService']['GetProgress']();
}

export function OpenDestinationFolder(arg1) {
  return window['go']['importer']['ImportService']['OpenDestinationFolder'](arg1);
}

export function RunImport(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['importer']['ImportService']['RunImport'](arg1, arg2, arg3, arg4, arg5);
}

export function ScanFiles(arg1, arg2) {
  return window['go']['importer']['ImportService']['ScanFiles'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['importer']['ImportService']['Startup'](arg1);
}
