// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {importer} from '../models';
import {context} from '../models';

export function CancelImport():Promise<void>;

export function GenerateThumbnail(arg1:string):Promise<string>;

export function GenerateThumbnailsForFiles(arg1:Array<string>,arg2:number):Promise<Record<string, string>>;

export function GetProgress():Promise<importer.ImportProgress>;

export function OpenDestinationFolder(arg1:string):Promise<void>;

export function RunImport(arg1:string,arg2:string,arg3:Array<string>,arg4:string,arg5:boolean):Promise<void>;

export function ScanFiles(arg1:string,arg2:Array<string>):Promise<Array<importer.FileInfo>>;

export function Startup(arg1:context.Context):Promise<void>;
